stages:
  - build_bin
  - build_rpm

build_bin:
  stage: build_bin
  image: 192.168.30.226/yunke-slb-ingress/rpmbuild:1.0
  variables:
    DOCKER_AUTH_CONFIG: '{"auths": {"192.168.30.226": {"auth": "emhhb3lnZjpaaGFveWdmMTIzNDU="}}}'
#  image: gcc:4.8.5   # gcc 版本
  script:
    - sudo chmod +x ./build_cc.sh ./configure
    - sudo ./build_cc.sh -t $CI_COMMIT_SHA -d conf
    - sudo make -j `nproc`
    - sudo ./build_cc.sh install
    - sudo chmod +x ./build_lua.sh
    - sudo mkdir -p objs/scripts/register/
    - sudo ./build_lua.sh
    - sudo mkdir -p work/usr/local/lib/   # 创建文件包目录
    - sudo cp -a /usr/local/njet work/usr/local/
    - sudo cp -a /usr/local/lib/* work/usr/local/lib/
  artifacts:
    paths:     # 需要打包的文件
      - objs/njet
      - objs/*.so
      - objs/scripts
      - work/*
    expire_in: 1 week # 打包文件存储有效期

build_rpm:
  stage: build_rpm
  image: 192.168.30.226/yunke-slb-ingress/rpmbuild:1.0
  variables:
    DOCKER_AUTH_CONFIG: '{"auths": {"192.168.30.226": {"auth": "emhhb3lnZjpaaGFveWdmMTIzNDU="}}}'
  when: manual
  script:
    - cd /builds/njet_dev/  
    - tar cf /home/builder/rpm/njet_main.tar --exclude="njet_main/.git" njet_main
    - sudo chmod +x /builds/njet_dev/njet_main/build/rpm/generate_njet_spec.sh
    - cd /builds/njet_dev/njet_main/build/rpm && NJT_BUILD_OPT="-t $CI_COMMIT_SHA" ./generate_njet_spec.sh  && cd - 
    - cp /builds/njet_dev/njet_main/build/rpm/njet.spec /home/builder/rpm/ 
    - rpmbuild -bb /home/builder/rpm/njet.spec
    - cd /builds/njet_dev/njet_main 
    - sudo mkdir -p work 
    - sudo cp -a /home/builder/rpm/x86_64/*.rpm work/ 
  artifacts:
    paths: # 需要打包的文件
      - work/*.rpm
    expire_in: 1 week # 打包文件存储有效期
